# Generated by Django 4.2.5 on 2023-09-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='category_n',
            new_name='category',
        ),
    ]
